# Basic
title: Fynil
subtitle: åˆä¸æ˜¯ä¸èƒ½ç”¨ğŸ¶
welcome_message: <a href="https://github.com/fynil" target="_blank">Fynil</a>
description: æ‡’ç™Œæ™šæœŸçš„å¤œçŒ«å­ï¼Œå†™ä¸å‡ºå¥½ç¨‹åºçš„ç å†œï¼Œå”±ä¸ä¸Šé«˜éŸ³ï¼Œå­¦ä¸ä¼šå‰ä»–æŒ‡å¼¹çš„éŸ³ä¹çˆ±å¥½è€… ï¼Œæš‚æ—¶åœ¨å¼€å‘ iOSï¼ŒğŸ’Š
creator: <a href="http://fynil.cn">@Fynil</a>

url: "https://github.com/Fynil"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: å…³äº, description: My Projects, url: 'http://github.com/fynil'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: westplace
    github: Fynil
    mail: fynil@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
