# Basic
title: Even Lin
subtitle: æˆ‘ç»§ç»­
welcome_message: <a href="http://fynil.cn" target="_blank">@EvenLin's Blog</a>
description: å“ˆå–½ï¼ŒI AM Even Linï¼Œæ¥è‡ªæ­å·çš„ iOS Developerï¼Œè¿˜æ˜¯æ‡’ç™Œæ™šæœŸçš„å¤œçŒ«å­ï¼Œå”±ä¸ä¸Šé«˜éŸ³ï¼Œå­¦ä¸ä¼šå‰ä»–æŒ‡å¼¹çš„éŸ³ä¹çˆ±å¥½è€…ã€‚å‘µï¼ŒğŸ’Š
creator: <a href="http://fynil.cn">@EvenLin</a>

url: "http://fynil.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: åšå®¢
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: å…³äº, description: My Projects, url: 'https://github.com/fynil'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: westplace
    github: evenlinyf
    mail: evenlinyf@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
